import {
  appName,
  contractVersion,
  jsonResponse,
  optionsResponse,
  timestamp,
} from "../../api-metadata";

export function GET() {
  return jsonResponse({
    appName,
    status: "success",
    contractVersion,
    identityMode: "workspaceId+userId",
    professionalIdRequired: false,
    usesLegacyEventNames: false,
    usesReportTerminology: true,
    canonicalOwnershipChecked: true,
    canonicalDraftOwnership: {
      postDraft: true,
      messageDraft: true,
      messageDraftScope: "simple_business_initiated_contact_or_followup_only",
      communicationReplyDraft: false,
      communicationSafetyCheck: false,
      communicationConversation: false,
      communicationConversationContext: false,
      customerMaster: false,
      reservationSourceOfTruth: false,
      paymentSourceOfTruth: false,
      salesSourceOfTruth: false,
      velvetProfessionalMemory: false,
      velvetVisit: false,
    },
    communicationPlannerBoundary: {
      communicationPlannerRecognized: true,
      snsPlannerPrimaryResponsibility: [
        "PostDraft",
        "post_text",
        "hashtags",
        "sns_specific_formatting",
        "post_schedule",
      ],
      snsMessageDraftScope: [
        "growth_engine_simple_followup_copy",
        "campaign_originated_simple_contact_copy",
        "message_copy_without_live_conversation_history",
      ],
      delegatedToCommunicationPlanner: [
        "live_conversation",
        "unified_inbox",
        "conversation_context",
        "reply_draft",
        "safety_check",
        "channel_send",
        "cross_person_context_mixing_prevention",
      ],
      receivesFullConversationHistories: false,
      ownsReplyDraft: false,
      ownsSafetyCheck: false,
      sendsMessages: false,
    },
    supportedProfessionalApps: ["numeria", "velvet"],
    velvetContractAlignment: {
      professionalApp: true,
      supportedAsMessageDraftTarget: true,
      velvetEventsObservedByReference: [
        "velvet.visit.started.v1",
        "velvet.visit.completed.v1",
        "velvet.memory.updated.v1",
        "velvet.note.created.v1",
        "velvet.next_action.created.v1",
      ],
      ownsVelvetVisit: false,
      ownsVelvetMemory: false,
      receivesFullVelvetNotes: false,
      receivesFullVelvetMemoryBodies: false,
    },
    supportedOperations: [
      "PostDraft.Generate",
      "PostDraft.Rewrite",
      "PostDraft.Metadata",
      "MessageDraft.Generate",
      "MessageDraft.Rewrite",
      "MessageDraft.Metadata",
      "PostTemplate.List",
    ],
    supportedEndpoints: [
      "GET /health",
      "GET /version",
      "GET /contracts/status",
      "GET /api/post-drafts",
      "GET /api/post-drafts/metadata",
      "POST /api/post-drafts",
      "GET /api/message-drafts",
      "GET /api/message-drafts/metadata",
      "POST /api/message-drafts",
    ],
    supportedEvents: [
      "sns.post_draft.created.v1",
      "sns.post_draft.updated.v1",
      "sns.message_draft.created.v1",
      "sns.message_draft.updated.v1",
    ],
    messageDraftContractStatus: "stable",
    formalContracts: {
      apiCatalog: [
        "MessageDraft.Generate",
        "MessageDraft.Rewrite",
        "MessageDraft.Metadata",
      ],
      eventCatalog: [
        "sns.message_draft.created.v1",
        "sns.message_draft.updated.v1",
      ],
    },
    observability: {
      traceHeaders: true,
      corsOptions: true,
      inboundApiLogs: true,
      outboundApiLogs: true,
      eventPublishedLogs: true,
      statusVocabulary: ["success", "warning", "error", "skipped"],
      environmentLimitationCode: "ENVIRONMENT_LIMITATION",
    },
    prohibitedPayloadFields: [
      "customerMasterRecords",
      "paymentStatus",
      "salesAmount",
      "stripeSecret",
      "stripeData",
      "fullMeetingTranscript",
      "reportBody",
      "fullReportBody",
      "fullReportBodies",
      "confidentialMemo",
      "apiKey",
      "accessToken",
      "secretPrompt",
      "fullProfessionalNotes",
      "fullProfessionalMemory",
      "fullProfessionalNoteBody",
      "fullProfessionalMemoryBody",
      "liveConversation",
      "liveConversationContext",
      "unifiedInbox",
      "conversation",
      "conversationId",
      "conversationContext",
      "conversationContextBody",
      "fullConversationContext",
      "fullConversationHistory",
      "fullConversationHistories",
      "messageBody",
      "fullMessageBody",
      "replyDraft",
      "replyDraftId",
      "safetyCheck",
      "safetyCheckId",
      "sendWorkflow",
      "channelSend",
      "dmSend",
      "lineSend",
      "actualMessageSend",
      "crossPersonContext",
      "otherPersonContext",
      "velvetCustomerMaster",
      "paymentRecord",
      "paymentRecords",
      "salesRecord",
      "salesRecords",
    ],
    issues: [],
    timestamp: timestamp(),
  });
}

export function OPTIONS() {
  return optionsResponse();
}
