import { appName, contractVersion, jsonResponse, optionsResponse, timestamp } from "../../../api-metadata";

export function GET() {
  return jsonResponse({
    appName,
    supported: true,
    draftType: "MessageDraft",
    contractVersion,
    status: "success",
    contractStatus: "stable",
    operation: "MessageDraft.Metadata",
    operations: [
      "MessageDraft.Generate",
      "MessageDraft.Rewrite",
      "MessageDraft.Metadata",
    ],
    endpoint: "GET /api/message-drafts/metadata",
    generateEndpoint: "POST /api/message-drafts",
    sourceApp: "growth-engine",
    targetApp: "sns-planner",
    supportedChannels: ["line", "instagram_dm", "email", "sms", "other"],
    supportedPurposes: [
      "reservation_reminder",
      "followup",
      "follow_up",
      "repeat_visit",
      "campaign_notice",
      "thank_you",
      "inactive_customer",
    ],
    supportedTones: [
      "polite",
      "friendly",
      "concise",
      "warm",
      "professional",
      "casual",
      "premium",
      "gentle",
    ],
    supportedTargetStudios: ["numeria", "velvet"],
    supportedAudienceSegments: [
      "new_lead",
      "first_time_customer",
      "repeat_customer",
      "repeat_candidate",
      "inactive_customer",
      "high_value_customer",
    ],
    supportedCtas: [
      "booking_page",
      "book_next_visit",
      "reply_request",
      "visit_request",
      "consultation_request",
    ],
    supportedProfessionalApps: [
      {
        appName: "numeria-studio",
        targetStudio: "numeria",
        supportedByContract: true,
      },
      {
        appName: "velvet",
        targetStudio: "velvet",
        supportedByContract: true,
      },
    ],
    messageDraftScope: {
      role: "simple_business_initiated_contact_or_followup_draft",
      allowedUseCases: [
        "growth_engine_simple_followup_copy",
        "campaign_originated_simple_contact_copy",
        "message_copy_without_live_conversation_history",
      ],
      notFor: [
        "live_conversation",
        "unified_inbox",
        "conversation_context",
        "reply_draft",
        "safety_check",
        "channel_send",
        "cross_person_context_check",
      ],
      delegatedOwner: {
        liveConversation: "communication-planner",
        unifiedInbox: "communication-planner",
        conversationContext: "communication-planner",
        replyDraft: "communication-planner",
        safetyCheck: "communication-planner",
        channelSend: "communication-planner",
        crossPersonContextMixingPrevention: "communication-planner",
      },
    },
    communicationPlannerBoundary: {
      ownsLiveConversation: false,
      ownsUnifiedInbox: false,
      ownsConversationContext: false,
      ownsReplyDraft: false,
      ownsSafetyCheck: false,
      sendsMessages: false,
      preventsCrossPersonContextMixing: false,
      owner: "communication-planner",
    },
    velvetContractAlignment: {
      sourceOfTruth: {
        visit: false,
        memory: false,
        note: false,
        nextAction: false,
      },
      acceptedReferences: [
        "customerId",
        "reservationId",
        "visitScheduleId",
        "visitId",
        "noteId",
        "summaryRef",
        "nextActionRef",
        "followupId",
        "campaignId",
      ],
      relatedEvents: [
        "velvet.visit.started.v1",
        "velvet.visit.completed.v1",
        "velvet.memory.updated.v1",
        "velvet.note.created.v1",
        "velvet.next_action.created.v1",
      ],
      payloadMode: "reference_first",
    },
    events: [
      "sns.message_draft.created.v1",
      "sns.message_draft.updated.v1",
    ],
    sourceOfTruth: {
      messageDraft: true,
      customer: false,
      payment: false,
      sales: false,
    },
    requiredFields: [
      "workspaceId",
      "userId",
      "sourceApp",
      "targetStudio",
      "channel",
      "purpose",
      "audienceSegment",
      "tone",
      "cta",
      "inputRef",
    ],
    prohibitedPayloadFields: [
      "customer",
      "customerMaster",
      "customerMasterRecords",
      "customerProfile",
      "paymentStatus",
      "salesAmount",
      "stripeSecret",
      "stripeData",
      "fullMeetingTranscript",
      "reportBody",
      "fullReportBody",
      "fullReportBodies",
      "confidentialMemo",
      "fullProfessionalNotes",
      "fullProfessionalMemory",
      "fullProfessionalNoteBody",
      "fullProfessionalMemoryBody",
      "liveConversation",
      "liveConversationContext",
      "unifiedInbox",
      "conversation",
      "conversationId",
      "conversationContext",
      "conversationContextBody",
      "fullConversationContext",
      "fullConversationHistory",
      "fullConversationHistories",
      "messageBody",
      "fullMessageBody",
      "replyDraft",
      "replyDraftId",
      "safetyCheck",
      "safetyCheckId",
      "sendWorkflow",
      "channelSend",
      "dmSend",
      "lineSend",
      "actualMessageSend",
      "crossPersonContext",
      "otherPersonContext",
      "velvetCustomerMaster",
      "paymentRecord",
      "paymentRecords",
      "salesRecord",
      "salesRecords",
      "apiKey",
      "accessToken",
      "secretPrompt",
    ],
    aiPlatformCoreActivity: {
      targetApp: "ai-platform-core",
      endpoint: "POST /api/activities",
      sourceApp: "sns-planner",
      activityType: "sns.message_draft.created",
      capability: "sns.message.generate",
      inputMode: "reference_ids_only",
    },
    timestamp: timestamp(),
  });
}

export function OPTIONS() {
  return optionsResponse();
}
